kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "admin-view.fullname" . }}
  labels:
    {{- include "admin-view.labels" . | nindent 4 }}
data:
  AWS_REGION: {{ .Values.region | default "ap-south-1" }}
  QUEUE_URL: {{ .Values.sqs_queue_url | default "https://sqs.ap-south-1.amazonaws.com/885234883381/admin-view" }}