kind: ConfigMap
apiVersion: v1
metadata:
metadata:
  name: {{ include "admin-view.fullname" . }}
  labels:
    {{- include "admin-view.labels" . | nindent 4 }}
data:
  AWS_REGION: {{ .Values.region | default "ap-south-1" }}
  SQS_QUEUE_URL: {{ .Values.sqs_queue_url | default "https://sqs.ap-south-1.amazonaws.com/885234883381/admin-view" }}
  DB_HOST: {{ .Values.db_host | default "ap-south-1" }}
  DB_USER: {{ .Values.db_user | default "ap-south-1" }}
  DB_TABLE: {{ .Values.db_table | default "ap-south-1" }}
  DB_NAME: {{ .Values.db_name | default "ap-south-1" }}
