apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "admin-view.fullname" . }}
  labels:
    {{- include "admin-view.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: dev-sqs-consumer.filmymoji.store
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: sqs-consumer
            port:
              number: 80
